require "tools-cf-plugin/watch"
require "tools-cf-plugin/shell"
require "tools-cf-plugin/dea-ads"
require "tools-cf-plugin/dea-apps"
require "tools-cf-plugin/tunnel/tunnel-nats"
require "tools-cf-plugin/tunnel/watch-logs"
require "tools-cf-plugin/spacetime"
